name: Run Test Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: 23f3004407@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: Finish
        run: echo "GitHub Actions workflow completed."
